#!/usr/bin/env bash

set -euo pipefail

if [[ $# -ne 2 ]]; then
    echo "Usage: $0 <threads> <repetitions>"
    exit 1
fi

THREADS="$1"
REPETITIONS="$2"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

QUOTIENT="${ROOT_DIR}/build/quotient"
DATA_DIR="${ROOT_DIR}/data"
RESULTS_DIR="${ROOT_DIR}/results/experiment2"


DATASETS=(
    ecoli400
    ecoli800
    ecoli1600
    ecoli3412
)


declare -A K_VALUES=(
    [ecoli400]=267
    [ecoli800]=371
    [ecoli1600]=533
    [ecoli3412]=745
)

if [[ ! -x "${QUOTIENT}" ]]; then
    echo "Error: quotient executable not found:"
    echo "  ${QUOTIENT}"
    exit 1
fi

mkdir -p "${RESULTS_DIR}"

echo "Experiment 2"
echo "Threads:     ${THREADS}"
echo "Repetitions: ${REPETITIONS}"
echo "Mode:        external memory (-e)"
echo

for dataset in "${DATASETS[@]}"; do
    DATASET_DIR="${RESULTS_DIR}/${dataset}"
    mkdir -p "${DATASET_DIR}"

    INPUT="${DATA_DIR}/${dataset}.fa"
    K="${K_VALUES[$dataset]}"

    echo "Dataset: ${dataset}"
    echo "  k: ${K}"

    for ((run = 1; run <= REPETITIONS; run++)); do
        LOG="${DATASET_DIR}/run_${run}.log"
        IO_FILE="${DATASET_DIR}/run_${run}.io"
        PID_FILE="${DATASET_DIR}/run_${run}.pid"
        OUTPUT="${DATASET_DIR}/output.gfa"

        echo "  Run ${run}/${REPETITIONS}"

        rm -f "${OUTPUT}" "${PID_FILE}"

        if [[ "${run}" -eq 1 ]]; then
            rm -f "${IO_FILE}"
        fi

         /usr/bin/time -v \
            bash -c '
                cd "$1"
                echo "$$" > "$2"
                exec "$3" \
                    -i "$4" \
                    -o "$5" \
                    -k "$6" \
                    -t "$7" \
                    -e
            ' _ \
            "${DATASET_DIR}" \
            "${PID_FILE}" \
            "${QUOTIENT}" \
            "${INPUT}" \
            "${OUTPUT}" \
            "${K}" \
            "${THREADS}" \
            > "${LOG}" 2>&1 &

        TIME_PID=$!

        while [[ ! -s "${PID_FILE}" ]]; do
            sleep 0.01
        done

        PID="$(cat "${PID_FILE}")"

        # Disk I/O and logical I/O are measured only for the first run.
        if [[ "${run}" -eq 1 ]]; then
            while kill -0 "${PID}" 2>/dev/null; do
                if [[ -r "/proc/${PID}/io" ]]; then
                    cat "/proc/${PID}/io" > "${IO_FILE}"
                fi
                sleep 0.1
            done

            if [[ -r "/proc/${PID}/io" ]]; then
                cat "/proc/${PID}/io" > "${IO_FILE}"
            fi
        fi

        wait "${TIME_PID}"

        # Storage is measured only after the first invocation.
        # It includes the input dataset and all files generated by quotient.
        if [[ "${run}" -eq 1 ]]; then
            INPUT_SIZE="$(
                du -sb "${INPUT}" |
                awk '{print $1}'
            )"

            GENERATED_SIZE="$(
                du -sb \
                    --exclude='run_*.log' \
                    --exclude='run_*.io' \
                    --exclude='run_*.pid' \
                    --exclude='storage.txt' \
                    "${DATASET_DIR}" |
                awk '{print $1}'
            )"

            echo "${INPUT_SIZE}" > "${DATASET_DIR}/input_size.txt"
            echo "${GENERATED_SIZE}" > "${DATASET_DIR}/generated_size.txt"
        fi

        # Remove everything generated by quotient.
        # Keep logs and measurements.
        find "${DATASET_DIR}" \
            -mindepth 1 \
            -maxdepth 1 \
            ! -name 'run_*.log' \
            ! -name 'run_*.io' \
            ! -name 'input_size.txt' \
            ! -name 'generated_size.txt' \
            -exec rm -rf {} +

        # The experiments reported in the paper cleared the filesystem
        # cache between runs. This requires elevated privileges on the host.
        #
        # sync
        # sudo sh -c 'echo 3 > /proc/sys/vm/drop_caches'
    done

    echo
done

SUMMARY="${RESULTS_DIR}/summary.csv"

echo "dataset,Time (mm:ss),RSS (GB),Disk Read (GB),Disk Write (GB),Logical Read (GB),Logical Write (GB),Storage (GB)" \
    > "${SUMMARY}"

median() {
    sort -n |
        awk '
            {
                values[NR] = $1
            }
            END {
                if (NR % 2 == 1)
                    printf "%.6f\n", values[(NR + 1) / 2]
                else
                    printf "%.6f\n", \
                        (values[NR / 2] + values[NR / 2 + 1]) / 2
            }
        '
}

for dataset in "${DATASETS[@]}"; do
    DATASET_DIR="${RESULTS_DIR}/${dataset}"
    TOTAL_TIMES=()

    for ((run = 1; run <= REPETITIONS; run++)); do
        LOG="${DATASET_DIR}/run_${run}.log"

        WALL_TIME="$(
            grep 'Elapsed (wall clock) time' "${LOG}" |
            sed 's/.*: //' |
            tail -n 1
        )"

        WALL_SECONDS="$(
            awk -F: '
                {
                    if (NF == 2)
                        printf "%.6f\n", $1 * 60 + $2
                    else
                        printf "%.6f\n", $1 * 3600 + $2 * 60 + $3
                }
            ' <<< "${WALL_TIME}"
        )"

        TOTAL_TIMES+=("${WALL_SECONDS}")
    done

    TIME_MEDIAN="$(
        printf '%s\n' "${TOTAL_TIMES[@]}" |
        median
    )"

    TIME_MMSS="$(
        awk -v seconds="${TIME_MEDIAN}" '
            BEGIN {
                minutes = int(seconds / 60)
                remaining = seconds - minutes * 60
                printf "%02d:%05.2f", minutes, remaining
            }
        '
    )"

    FIRST_LOG="${DATASET_DIR}/run_1.log"

    RSS_KB="$(
        grep 'Maximum resident set size (kbytes)' "${FIRST_LOG}" |
        awk '{print $NF}' |
        tail -n 1
    )"

    RSS_GB="$(
        awk -v rss="${RSS_KB}" '
            BEGIN {
                printf "%.6f\n", rss / 1024 / 1024
            }
        '
    )"

    IO_FILE="${DATASET_DIR}/run_1.io"

    READ_BYTES="$(
        grep '^read_bytes:' "${IO_FILE}" |
        awk '{print $2}'
    )"

    WRITE_BYTES="$(
        grep '^write_bytes:' "${IO_FILE}" |
        awk '{print $2}'
    )"

    RCHAR="$(
        grep '^rchar:' "${IO_FILE}" |
        awk '{print $2}'
    )"

    WCHAR="$(
        grep '^wchar:' "${IO_FILE}" |
        awk '{print $2}'
    )"

    DISK_READ_GB="$(
        awk -v value="${READ_BYTES}" '
            BEGIN {
                printf "%.6f\n", value / 1024 / 1024 / 1024
            }
        '
    )"

    DISK_WRITE_GB="$(
        awk -v value="${WRITE_BYTES}" '
            BEGIN {
                printf "%.6f\n", value / 1024 / 1024 / 1024
            }
        '
    )"

    LOGICAL_READ_GB="$(
        awk -v value="${RCHAR}" '
            BEGIN {
                printf "%.6f\n", value / 1024 / 1024 / 1024
            }
        '
    )"

    LOGICAL_WRITE_GB="$(
        awk -v value="${WCHAR}" '
            BEGIN {
                printf "%.6f\n", value / 1024 / 1024 / 1024
            }
        '
    )"

    INPUT_SIZE="$(cat "${DATASET_DIR}/input_size.txt")"
    GENERATED_SIZE="$(cat "${DATASET_DIR}/generated_size.txt")"

    STORAGE_GB="$(
        awk \
            -v input="${INPUT_SIZE}" \
            -v generated="${GENERATED_SIZE}" '
            BEGIN {
                printf "%.6f\n", \
                    (input + generated) / 1024 / 1024 / 1024
            }
        '
    )"

    echo "${dataset},${TIME_MMSS},${RSS_GB},${DISK_READ_GB},${DISK_WRITE_GB},${LOGICAL_READ_GB},${LOGICAL_WRITE_GB},${STORAGE_GB}" \
        >> "${SUMMARY}"
done

echo
echo "Experiment completed."
echo
echo "Summary:"
cat "${SUMMARY}"
echo
echo "Results stored in:"
echo "  ${RESULTS_DIR}"
